docs: update `getting-started` guide
open-sauced/intro pull request #104
Opened 2024-01-10 06:42 UTC by at-the-vr

## Description

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Closes #103 

## Steps to QA

1. Open the PR in GitPod
2. Use Live Server or Markdown Live Preview extension to see the suggested changes
3. Validate the changes, find any discrepancies and provide suggestions

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed
- [x] 📝 [05-how-to-contribute-to-open-source](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started)

2024-01-11 15:01 UTC, BekahHW requested changes
Hey @at-the-vr! Thanks for taking on this issue. Would you mind removing the extra space after line seven and making guest book one word? We realized in reviewing your PR that we had it written both ways, but we're going to make it consistent throughout the repo with one word. Thanks so much for getting in this PR! Everything else is great.

2024-01-11 15:03 UTC, BekahHW commented on 05-how-to-contribute-to-open-source.md
> +
Can you remove this space?

2024-01-11 15:05 UTC, BekahHW commented on 05-how-to-contribute-to-open-source.md
> +2. Fork the [guest book repository](https://github.com/open-sauced/guestbook).
And also remove the space between lines 2 and 3.

2024-01-11 15:42 UTC, CBID2 approved these changes
Looks ok to me! :) What do you think @BekahHW?

2024-01-12 19:11 UTC, BekahHW approved these changes

2024-01-12 19:11 UTC, BekahHW commented
Great job, @at-the-vr !

2024-01-12 19:11 UTC, merged