Added a note to fill PR form in lesson 05
open-sauced/intro pull request #141
Opened 2024-03-24 13:36 UTC by Haimantika

## Description

This solves issue https://github.com/open-sauced/intro/issues/140 , where I added a note to fill PR form in lesson 05

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
https://github.com/open-sauced/intro/issues/140

## Mobile & Desktop Screenshots/Recordings

NA

## Steps to QA

NA

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-03-24 17:14 UTC, CBID2 commented
Hey @Haimantika. Can you add `Closes` next to the issue number in the `Related Tickets and Documents section`?

2024-03-24 18:38 UTC, adiati98 commented
@Haimantika I think your PR here consists the previous commits from your changes on PR #133.

Can you try to pull and merge the `main` from upstream to your working branch (`fix_lesson_5`)?
Thank you.

2024-03-24 18:49 UTC, Haimantika commented
> git pull

Oh thanks, so nothing pending from my end, right?

2024-03-24 18:53 UTC, adiati98 requested changes
Hi @Haimantika,
Thank you for your PR! 🙌

I left a review here for you to fix before we can approve your PR.
I also updated your branch. So, can you please pull your branch before working on the fix?

Let me know when it's fixed and ready for a review.
Thank you. 🙂

2024-03-24 18:53 UTC, adiati98 commented on 05-how-to-contribute-to-open-source.md
> +   !> Your pull request will be marked as invalid and may be closed if the form is incomplete.
We want to apply the suggestion on the issue. So, can you please:

1. Update the wording in point 11.
2. Add space for the alert.

```suggestion
11. Go to your forked repository on GitHub. Create a pull request with the title `feat: Add <@github-username> as a contributor` and fill in all areas in the pull request form.

   !> Your pull request will be marked as invalid and may be closed if the form is incomplete.
```

2024-03-24 18:54 UTC, Haimantika commented
> Hi @Haimantika, Thank you for your PR! 🙌
> 
> I left a review here for you to fix before we can approve your PR. I also updated your branch. So, can you please pull your branch before working on the fix?
> 
> Let me know when it's fixed and ready for a review. Thank you. 🙂

Accepted changes.

2024-03-24 18:57 UTC, adiati98 approved these changes
Thanks, @Haimantika! 🙌

![git merge GIF](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

2024-03-25 15:46 UTC, BekahHW approved these changes

2024-03-25 17:08 UTC, merged