Fix dynamic `editUrl` path for documentation subfolder structure
open-sauced/intro pull request #247
Opened 2024-10-05 06:25 UTC by Codexnever

### Description:
This pull request addresses an issue with the `editUrl` configuration in the `docusaurus.config.js` file, where the `editUrl` was incorrectly concatenating the paths for editing the documentation. The issue was observed when the documentation structure was split into multiple subfolders, but the correct path was not reflected in the edit links.

#### Problem:
When attempting to edit documentation from the site, the generated edit URL was appending paths incorrectly. For example, it was redirecting users to:
```
https://github.com/open-sauced/intro/blob/main/docs/intro-to-oss/README.md/docs/intro-to-oss/README.md
```
This resulted in a broken link because of the duplicate path segments.

#### Solution:
1. **Dynamic Path Handling**: Updated the `editUrl` on line 47 of the `docusaurus.config.js` file to handle the subfolder structure dynamically. The `editUrl` now accurately reflects the path by properly concatenating the correct segments of the URL.
   
2. **Folder Structure**: The course documentation was split into two subfolders, which wasn't properly handled in the `editUrl` path. The issue has now been resolved by making the `editUrl` match the actual structure of the docs subfolder.

### Changes Made:
- Modified the `editUrl` on line 47 of the `docusaurus.config.js` to dynamically handle the subfolder structure.
- Ensured that the URL correctly redirects to the `main` branch of the GitHub repository for the documentation:
   ```
   https://github.com/open-sauced/intro/blob/main/docs/intro-to-oss/README.md
   ```

### Verification:
- Verified that the changes work locally by testing the documentation edit links in the Docusaurus site. The edit links now correctly redirect to the respective documentation files in the GitHub repository.
  
### Affected Files:
- `docusaurus.config.js`: Corrected the `editUrl` configuration to prevent path duplication and broken links.

### Related Issues:
Close #241 
---

2024-10-07 09:45 UTC, adiati98 reviewed
Hey @Codexnever,
Thank you for your PR! ✨ 

I've tested this out locally, and it works well. 👍🏼 
As @BekahHW mentioned:

> You can create the PR if it's working locally.

let's stick to that. 
 
I see that you made some other changes here that are not required in the issue. Is there any reason for making these changes?

2024-10-07 09:45 UTC, adiati98 commented on docusaurus.config.js
> +          sidebarPath: require.resolve('./sidebars.js'),
**question:** Is there any reason to modify the `sidebarPath`? I don't see it's related to the issue.

2024-10-07 09:45 UTC, adiati98 commented on package-lock.json
I'm not sure if we want to change anything in our `package-lock.json` file. I'll let @BekahHW to decide here.

2024-10-07 10:08 UTC, adiati98 commented
@BekahHW, I just have some thoughts here after taking a closer look, and would love your feedback.

When folks click the "Edit this page" link, they will be redirected to the page where they can edit their changes **directly on the `main` branch of the original repo**. And we don't want them to make any changes directly in the original repo and `main` branch.

![edit page on github](https://github.com/user-attachments/assets/28ed8958-6f01-4b38-8a97-a3e2fb5475cc)

Some docs have this link on their website. However, most of them redirect folks to a page asking contributors to fork the repo to make changes. Let's take [Algolia DocSearch](https://docsearch.algolia.com/) as an example. The link redirects to [this page](https://github.com/algolia/docsearch/edit/main/packages/website/docs/what-is-docsearch.md) (see the screenshot below). 

![Screenshot 2024-10-07 120107](https://github.com/user-attachments/assets/9d4e3c54-ed61-4ea6-8c46-d40a02be7538)

I think we can adapt this method for this intro repo to encourage folks to improve our website while preventing any direct changes.

2024-10-07 13:57 UTC, BekahHW commented
> @BekahHW, I just have some thoughts here after taking a closer look, and would love your feedback.
> 
> When folks click the "Edit this page" link, they will be redirected to the page where they can edit their changes **directly on the `main` branch of the original repo**. And we don't want them to make any changes directly in the original repo and `main` branch.
> 
> ![edit page on github](https://private-user-images.githubusercontent.com/45172775/374119735-28ed8958-6f01-4b38-8a97-a3e2fb5475cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDk1NDAsIm5iZiI6MTcyODMwOTI0MCwicGF0aCI6Ii80NTE3Mjc3NS8zNzQxMTk3MzUtMjhlZDg5NTgtNmYwMS00YjM4LThhOTctYTNlMmZiNTQ3NWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEzNTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZmI3OThkNmEyODllYzk3ZjFhYjQ1YzM4NGU3MDVlYjMxYmI3YzdkYmFlNWRkMGY1YzZiODA3NzU3ZTQ5NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hr3WAmPU-PcpUFl6X6BC05Hdi1hDUJuvlgoGSnXQy2E)
> 
> Some docs have this link on their website. However, most of them redirect folks to a page asking contributors to fork the repo to make changes. Let's take [Algolia DocSearch](https://docsearch.algolia.com/) as an example. The link redirects to [this page](https://github.com/algolia/docsearch/edit/main/packages/website/docs/what-is-docsearch.md) (see the screenshot below).
> 
> ![Screenshot 2024-10-07 120107](https://private-user-images.githubusercontent.com/45172775/374123160-9d4e3c54-ed61-4ea6-8c46-d40a02be7538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDk1NDAsIm5iZiI6MTcyODMwOTI0MCwicGF0aCI6Ii80NTE3Mjc3NS8zNzQxMjMxNjAtOWQ0ZTNjNTQtZWQ2MS00ZWE2LThjNDYtZDQwYTAyYmU3NTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEzNTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMzRiNTkxODNhNzRiYjcwNjY0YmMyNzVkYmM2NWZiMGU1NWVhODZlYTM3ZmQyMzk2MDZmZjVjMWFhZjhiMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gKsWMuUjtBk6Fxh5Cl0OaWNmENJMi4mT_g0vTe6OMas)
> 
> I think we can adapt this method for this intro repo to encourage folks to improve our website while preventing any direct changes.

I think once the user completes the changes, this is what they should see bc it's a protected branch. So this shouldn't be a problem:

<img width="463" alt="image" src="https://github.com/user-attachments/assets/2a92ac5c-00c4-41da-9f7c-a784383f8be3">

2024-10-07 13:58 UTC, Codexnever commented on docusaurus.config.js
> +          sidebarPath: require.resolve('./sidebars.js'),
I didn't intend to modify sidebarPath I was exploring a potential solution, but if it's not needed, I can revert those changes

2024-10-07 14:15 UTC, BekahHW commented on package-lock.json
Yes, let's not make any changes that are not in the issue.

2024-10-07 15:17 UTC, Codexnever commented
Hi @BekahHW ,

After reflecting on @adiati98  comments, I think we can improve the "Edit this page" functionality. Here’s my proposal:

1. Redirect Users to Their Fork: For users who have already forked the repository, clicking "Edit this page" should take them directly to edit the README in their fork.
2. Guide New Users to Fork: For users who haven’t forked yet, the link can redirect them to the main repo to encourage them to fork it before making any edits.

This way, we ensure that edits are made in the appropriate context while helping new contributors understand the process better. What are your thoughts on this approach?

2024-10-08 17:51 UTC, BekahHW commented
@Codexnever I think it should automatically tell contributors that if we have the permissions set up properly. For example, when I try to edit a repo I don't have permission to directly in GH, this is what comes up:

<img width="819" alt="image" src="https://github.com/user-attachments/assets/232be8ef-f7b3-45b7-983c-bb6c0f78ced6">

Can you try to edit the Readme or one of the files in this project directly to see what happens?

2024-10-08 19:03 UTC, Codexnever commented
Hey @BekahHW,
Thanks for your feedback! I just tested the edit functionality by trying to make direct changes to the README, and it prompts the expected behavior, asking users to fork the repo if they don’t have direct permissions. I also reverted the unnecessary changes I made earlier, and you can check those in the latest commit.

2024-10-09 13:13 UTC, adiati98 requested changes
Hey @Codexnever,
You haven't revert the changes in the `package-lock.json`. Can you please revert to the original state? Thanks.

2024-10-09 13:13 UTC, adiati98 commented on package-lock.json
> +    "name": "@open-sauced/intro.opensauced.pizza",
As per our discussion, you need to revert this one.

2024-10-09 13:13 UTC, adiati98 commented on package-lock.json
> +            "name": "@open-sauced/intro.opensauced.pizza",
Also this one.

2024-10-09 15:31 UTC, Codexnever commented on package-lock.json
> +            "name": "@open-sauced/intro.opensauced.pizza",
Done

2024-10-09 19:29 UTC, BekahHW approved these changes

2024-10-10 07:04 UTC, merged