Fix : Update UI component for improved design
open-sauced/intro pull request #249
Opened 2024-10-12 21:15 UTC by Codexnever

Related Issue: Closes #243 

Summary of Changes:

Updated the UI of the card component to improve layout and responsiveness.
Added styles to enhance visual appeal and usability, ensuring the button is positioned at the bottom of the card.

#### Checklist

- [ ] Related issue linked with the keyword: "Closes", "Fixes", or "Resolves".
- [ ] All sections of the PR template are filled in.
- [ ] No sections of the PR template have been deleted. If irrelevant, responded with "N/A".

---

2024-10-13 08:51 UTC, adiati98 requested changes
Hi @Codexnever, please don't delete sections in the PR template.

You must complete the template, and when a section is not related to your PR, you can leave it blank.

Have you read all the comments in the PR template?
One of it says:

```markdown
<!-- note: PRs with deleted sections will be marked invalid -->
```

That being said, please fix your PR template before we review your PR. Alternatively, you can close this PR and create a new one.

Thank you. 🙂

2024-10-13 13:08 UTC, Codexnever commented
> Hi @Codexnever, please don't delete sections in the PR template.
> 
> You must complete the template, and when a section is not related to your PR, you can leave it blank.
> 
> Have you read all the comments in the PR template? One of it says:
> 
> ```
> <!-- note: PRs with deleted sections will be marked invalid -->
> ```
> 
> That being said, please fix your PR template before we review your PR. Alternatively, you can close this PR and create a new one.
> 
> Thank you. 🙂



Hi @adiati98,

Thank you for your feedback! I apologize for the oversight and for deleting sections of the PR template. I will update the PR template to ensure that all sections are retained and follow the guidelines correctly

Thanks again for your understanding!  🙂

2024-10-13 14:49 UTC, adiati98 commented
Do let me know once you've fixed it. 👍🏼 
You can take a look at closed PRs to see what you've removed.

2024-10-13 15:50 UTC, Codexnever commented
I will update check and let me know if anything remain

2024-10-14 14:55 UTC, adiati98 commented
@Codexnever your PR should look like this.
 
![Screenshot 2024-10-14 165353](https://github.com/user-attachments/assets/65a22e09-0b37-4017-8820-d8f7d85679b6)

2024-10-14 17:59 UTC, Codexnever commented
> @Codexnever your PR should look like this.
> 
> ![Screenshot 2024-10-14 165353](https://private-user-images.githubusercontent.com/45172775/376293336-65a22e09-0b37-4017-8820-d8f7d85679b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MjgyNzcsIm5iZiI6MTcyODkyNzk3NywicGF0aCI6Ii80NTE3Mjc3NS8zNzYyOTMzMzYtNjVhMjJlMDktMGIzNy00MDE3LTg4MjAtZDhmN2Q4NTY3OWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDE3NDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NjI5ZjAyYzJiZjAyODMxODFjNTc4Zjk5NmM4ZTIwMGRlZmM4ZmU3NjBiYzQ4ZGRhMzAwODUzYjNmMmRhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5M98JGBMJS9oHkqac-MVKICuuv1StA1C76b-VLiTVTg)


Hey @adiati98 ,

Sorry for submitting the wrong template earlier. Now i corrected you can check

Thanks for understanding!

Best,
Chaitanya

2024-10-15 14:36 UTC, BekahHW commented on package-lock.json
Hey @Codexnever can you explain what's going on with the package-lock.json here?

2024-10-15 15:20 UTC, Codexnever commented on package-lock.json
Hey @BekahHW ,

The changes in the package-lock.json might have been due to running npm install after making updates. I didn't intend to modify any dependencies directly, so I’ll take a closer look to make sure there’s nothing unexpected.

Let me know if you have any specific concerns!

2024-10-23 19:06 UTC, Codexnever commented on package-lock.json
Hi @adiati98 @BekahHW 

Is that any Update ?

2024-10-24 10:20 UTC, adiati98 commented on package-lock.json
@Codexnever have you taken a closer look to this? To be clear, we don't want to have any changes in this file.

2024-10-24 10:58 UTC, Codexnever commented on package-lock.json
@adiati98 Now i make changes in `package-lock-json` as per main branch.

2024-10-24 18:40 UTC, adiati98 approved these changes
Thank you for your contribution, @Codexnever! ✨ 

![thank you gif](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcXQ1cWgyejlxZXMwbzZwY2ZyNXUydWw5ZWgzaHp5d2VjZ204bGw5ZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/26gsjCZpPolPr3sBy/giphy-downsized.gif)

2024-10-24 20:18 UTC, BekahHW approved these changes

2024-10-24 20:19 UTC, merged